server:
  port: 8082
spring:
  thymeleaf:
    mode: LEGACYHTML5
    content-type: text/html
    cache: false
  redis:
    database: 12
    port: 6379
    host: 127.0.0.1
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
  application:
    name: sso-app2
sso:
  server:
    url: https://localhost:8080
  client:
    protect: /hello